# Generated by Django 3.0.3 on 2020-02-09 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='код')),
                ('currency', models.CharField(choices=[('usd', 'Доллар США'), ('cny', 'Юань'), ('eur', 'Евро')], default='usd', max_length=10, verbose_name='валюта')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_list', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'счет',
                'verbose_name_plural': 'счета',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_list', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('status', models.CharField(choices=[('initiated', 'Инициирован'), ('completed', 'Проведен'), ('declined', 'Отклонен')], max_length=10, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debit', 'Дебет'), ('credit', 'Кредит')], max_length=10, verbose_name='направление')),
                ('kind', models.CharField(choices=[('transfer', 'Перевод'), ('fee', 'Комиссия')], max_length=10, verbose_name='тип')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_list', to='billing.Account', verbose_name='счет')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_list', to='billing.Payment', verbose_name='платеж')),
            ],
            options={
                'verbose_name': 'операция',
                'verbose_name_plural': 'операции',
            },
        ),
    ]
