# Generated by Django 3.0.3 on 2020-02-09 21:24
from itertools import product

from django.db import migrations
from django.conf import settings


def fill_accounts(apps, schema_editor):
    Account = apps.get_model('billing', 'Account')

    for code, currency in product(settings.DEFAULT_ACCOUNT_LIST, settings.DEFAULT_CURRENCY_LIST):
        Account.objects.get_or_create(
            code=code,
            user=None,
            currency=currency,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_accounts),
    ]
